### ISSUE TITLE
logo size

### ISSUE THREAD

**Issue by Jimmy99** [zerostaticthemes/hugo-hero-theme#21]
Thanks for the great theme.
Can you direct me to where I scale the logo size? I have tried changing the details in the HEADER.html partial but the image size remains the same

**Comment by darwinanddavis** [comment]
You can change the logo size by either 1) changing the width in the assets/scss/components/_logo.scss file (same for the `.logo-mobile` component):

```
.logo {
  display: none;
  @include media-breakpoint-up(sm) {
    display: block;
    width: 120px;
  }
```
or 2) adjust the image size manually in an image editor. I use Inkscape for Mac OSX.
