### ISSUE TITLE
Subfooter has homepage hard coded

### ISSUE THREAD

**Issue by amalic** [zerostaticthemes/hugo-hero-theme#24]

**Comment by harenber** [comment]
copy sub-footer.html from ./themes/hero/layouts/partials/sub-footer.html into ./layouts/partials/ and adopt it to your needs. Worked in my case.

**Comment by JugglerX** [comment]
You can just delete line 7 `<li><a href="{{ .Site.BaseURL }}">Home</a></li>` from `partials/footer.html`

Or you could modify it to your needs.
