### ISSUE TITLE
Adding new sections?

### ISSUE THREAD

**Issue by tedhabermann** [zerostaticthemes/hugo-hero-theme#25]
I like the theme a lot but need a blog on my website. Is there documentation somewhere on adding a new section?

**Comment by JugglerX** [comment]
@tedhabermann I'm glad you like the theme, I don't plan to add a blog to it, there are hundreds of Hugo blog themes. 

With a bit of HTML/Hugo knowledge you can quite easily copy the blog section from another theme. Even try adding a `content/post` folder and adding a menu item might be enough to create the blog, havent tested it.
