### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by finnmglas** [zerostaticthemes/hugo-hero-theme#29]
Amazing work you're doing ^^

Just to make things smoother (improved UX) you should consider adding smooth scrolling:

```
html {
 scroll-behavior: smooth;
}
```

Pretty simple but it makes a great difference. Keep it up! 🚀

**Comment by JugglerX** [comment]
I don't know what this does. Is it really better UX? As long as it doesnt make it feel like one of those javascript smooth scrollers that make it take minutes to scroll then i guess its ok?

Feel free to do a PR.
