### ISSUE TITLE
Extra Paragraph Tags in /themes/hugo-hero-theme/layouts/index.html

### ISSUE THREAD

**Issue by linux4me** [zerostaticthemes/hugo-hero-theme#34]
In /themes/hugo-hero-theme/layouts/index.html, there are extra paragraph tags in two locations that cause invalid HTML.

The first is on line 31:
```
<p>{{ .Content }}</p>
```
and the second is on line 64:
```
<p>{{ .Content }}</p>
```
Wrapping the `{{ .Content }}` in paragraph tags means that all the content a user enters in the content section of a markdown file will be wrapped in additional `<p>` tags.

You can see the problem if you look at the source code for the Home page in the [demo](https://themes.gohugo.io/theme/hugo-hero-theme/), where the "We Help Business Grow" and "Our Difference" sections are both wrapped in unnecessary paragraph tags.

The fix--until this is fixed in the theme--seems to be simply removing the extra paragraph tags on lines 31 and 64, then saving the index.html file in the <your site>/layouts folder to override the theme's version.

**Comment by JugglerX** [comment]
fixed
