### ISSUE TITLE
Add hooks for custom.css

### ISSUE THREAD

**Issue by kmorrison** [zerostaticthemes/hugo-hero-theme#35]
I'm quite the hugo noob, but I love your theme and I'm using it to build my site. As with any site there's small tweaks I want to make, and it seems like these tweaks are kind of outside the scope of what hugo themes in general are trying to do. I got as far as https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/4, which seems to say that customizing css from themes is not that easy unless the theme developer specifically adds a hook for it. Is there something that I'm missing or is that what would be required for what I'm asking?

**Comment by RobertAlbus** [comment]
One option is to copy `themes/hugo-hero-theme/assets/scss/*` into your base project at `assets/scss/*`. From there you can customize the stylesheets to your hearts content and your generated site will use these overridden styles.  

This is what I did to achieve the same thing in my site that uses this theme.

**Comment by RoneoOrg** [comment]
See https://github.com/zerostaticthemes/hugo-hero-theme/pull/38

**Comment by JugglerX** [comment]
You can just edit the scripts.js or the scss files. What's the issue?

**Comment by flyingdan** [comment]
@RobertAlbus, to clarify, the project folder structure should be like this?

```
MyAwesomeWebsite
    archetypes
    assets
        scss
            components
                _filetoedit.scss
    config.toml
    content
    data
    layouts
    public
    resources
    static
    themes
```

Or do all the folders and files need to be copied into my project? Something like:

```
MyAwesomeWebsite
    archetypes
    assets
        scss
            components
                _<bunch of files>.scss
            libraries
            pages
    config.toml
    content
    data
    layouts
    public
    resources
    static
    themes
```
