### ISSUE TITLE
Bug: Permalink and RelPermalink are generating malformed URLs in build output (theme-specific)

### ISSUE THREAD

**Issue by RobertAlbus** [zerostaticthemes/hugo-hero-theme#37]
Hugo version: 0.870+extended
Problem exists in this theme, but not in a new theme when the relevant view templates and configs are ported in. Problem does not present itself when the site is viewed with `hugo server` but is present in build artifacts. It is present in other Hugo projects that use this theme.

`themes/hugo-hero-theme/layouts/_default/baseof.html:16-17` 
```
 {{ $style := resources.Get "scss/style.scss" | toCSS (dict "targetPath" "css/style.css" "enableSourceMap" false) }}
  <link rel="stylesheet" href="{{ ($style | minify | fingerprint).RelPermalink }}">
```

This code, when using `RelPermalink` OR `Permalink` results in the following output:
```
#build output
  <link rel="stylesheet" href="/mywebsite.com/css/style.min.1cd4c[...].css">
#local server output
  <link rel="stylesheet" href="//localhost:1313/css/style.css">
```
expected output:
```
  <link rel="stylesheet" href="/css/style.min.1cd4c[...].css">
  # or
  <link rel="stylesheet" href="mywebsite.com/css/style.min.1cd4c[...].css">
```
----------------
Followup:
When `BaseURL = /`, the build output results in a relative path 
```
  <link rel="stylesheet" href="/css/style.min.1cd4c[...].css">
```
regardless of whether or not you use `Permalink` or `RelPermalink`

**Comment by kontralto-rob** [comment]
@JugglerX Do you know why this might be happening?

**Comment by JugglerX** [comment]
@RobertAlbus @kontralto-rob I got different results.

In the `config.toml` I have a `baseURL = "www.example.com"`

Running locally `hugo serve` I get `<link rel="stylesheet" href="/css/style.min.f78f569c52930482d825f538adc06750cd316cb2520a7c9f09bc21535b65d628.css">`

Building the site, running `hugo` I get `<link rel="stylesheet" href="/www.example.com/css/style.min.4be821da6f580945734893eade9608940c6a2fa967507a70de1582d975493bc3.css">`

If I change the baseURL to have a http or https prefix ie `baseURL = "https://www.example.com"` It appears to fix it, I get `<link rel="stylesheet" href="/css/style.min.4be821da6f580945734893eade9608940c6a2fa967507a70de1582d975493bc3.css">`
