### ISSUE TITLE
Copyright text bad

### ISSUE THREAD

**Issue by Resonanz** [zerostaticthemes/hugo-hero-theme#40]
Copyright text has bad layout at reduced screen widths.

**Comment by JugglerX** [comment]
@Resonanz are you able to fix it and do a PR?

**Comment by jeremybettis** [comment]
Also the text is not aligned to the baseline. I fixed that by adding

```
ul.footer-menu {
  align-items: baseline;
}
```

**Comment by JugglerX** [comment]
fixed!
