### ISSUE TITLE
google font entry in config.toml not taking effect

### ISSUE THREAD

**Issue by Jimmy99** [zerostaticthemes/hugo-hero-theme#45]
I made the following entry in the config.toml to change the font but it's not taking effect. I copied the google_fonts entry from https://fonts.google.com/specimen/Jost. Can you see anything obvious that I've gotten wrong?:

[params.fonts]
    google_fonts = "https://fonts.googleapis.com/css2?family=Jost:wght@300&display=swap"
    heading = "Jost"
    base = "Jost"
    monospace = "Jost"

**Comment by JugglerX** [comment]
these params are not used by this theme
