### ISSUE TITLE
Landscape error just in homepage

### ISSUE THREAD

**Issue by DaveHenrys** [zerostaticthemes/hugo-hero-theme#50]
Hello,
thank you for this wonderful theme!

I noticed that part of the typo is cut off on mobile browsers in landscape view. 

https://hugo-hero.netlify.app/

I tested this with different browsers on iOS and Android. 

As this occurs only at the homepage this should be fixable. In which file do I have to change a value?

All the best
Dave

**Comment by DaveHenrys** [comment]
![landscape](https://user-images.githubusercontent.com/111613351/185734536-2a66c628-5cd9-4927-9d08-49c98b5d7e76.jpg)

**Comment by JugglerX** [comment]
@DaveHenrys did you get it fixed? Care to do a PR?
