### ISSUE TITLE
Hugo Hero Theme on mobile devices

### ISSUE THREAD

**Issue by hollidayc** [zerostaticthemes/hugo-hero-theme#61]
Hi, the down arrow on the home page of the theme is supposed to show at the bottom of the hero image but on mobile devices it is hidden by the device UI. I fixed it for my web site by amending _hero-image.scss to change .container to remove height and replace with min-height: 80dvh . I also animated the down arrow but that isn't essential for the fix. I attach my version of the file in case you want to use it. 
[_hero-image.scss.zip](https://github.com/zerostaticthemes/hugo-hero-theme/files/12043007/_hero-image.scss.zip)

**Comment by JugglerX** [comment]
A PR with you changes would be appreciated
