### ISSUE TITLE
Hard-coded "Our Services" in index template

### ISSUE THREAD

**Issue by tastapod** [zerostaticthemes/hugo-hero-theme#63]
The heading "Our Services" is hard-coded in the `layouts/index.html` [template][]. The other headings use `{{ .Title }}` which picks up the title from one of the reusable pages. It would make more sense to take the Services title from `/content/services/_index.md` using `{{ with .Site.GetPage "/services/" }}{{ .Title }}{{ end }}`.

I'm happy to provide a PR if you like.

[template]: /zerostaticthemes/hugo-hero-theme/blob/d18f9c97291a1dd8e7ba44b72300cde84df05fec/layouts/index.html#L44

**Comment by JugglerX** [comment]
Merged thankyou!
